### ISSUE TITLE
M3- SDK v2 - IDM sample isn’t working on a multi tenant environment.

### ISSUE THREAD

**Issue by jonathansanjuan** [infor-cloud/m3-h5-sdk#10]
**Describe the bug**
I’ve built the material sample "infor-m3-odin-sample-material-2.1.0", and deployed it to a multi tenant environment. The IDM sample isn’t working:

**To Reproduce**

1. install the /dist/ in the multi tenant environemnt
2. Open #/material/idm application
3. Click on user context sample and click 'load' to ensure session is running. Output values have to have values.
	4. Tested also with M3 in 'Customer' - it calls
		a. https://*.com/m3api-rest/execute/CRS610MI/LstByNumber;metadata=true;maxrecs=100;excludempty=false;cono=100;divi=100;returncols=CUNO,CUNM,TOWN,CUA1?_rid=*
		b. Data is shown in the list

	5. Click on IDM - the IDM sample loads, and also calls
	https://*.com/grid/rest/security/sessions/oauth?rid=*
	6. Also try "ION API Social" - pressing load calls
https://*.com/grid/rest/security/sessions/oauth?rid=* but nothing also happens
		
**Expected behavior**
The IDM sample should show a list of documents from IDM.
ION API Social should show data too.

**Version**
 - `@infor-up/m3-odin`: version 6.9.0
 - `@infor-up/m3-odin-angular`: version 6.9.0
 - `@infor-up/m3-odin-cli`: version 6.9.0

**Additional context**

Tested this in Chrome - but fiddler isn't recording it.  Tried the same from Firefox - same behaviour - but fiddler is able to record it.

fiddler log catching FireFox is in 
[https://inforonline-my.sharepoint.com/:u:/g/personal/jonathan_sanjuan_infor_com/Ea-1NxD6db1Psbqj0VIrrpEBkE7INWYuIogL2Zaf-Zj1Lw?e=mkgIx6](url)

Chrome console log:
[https://inforonline-my.sharepoint.com/:t:/g/personal/jonathan_sanjuan_infor_com/EbBeDb0-fAJPhpypf1-7HdcBA4dQctlulraVfK-MBTSozw?e=vlR229](url)

[https://inforonline-my.sharepoint.com/:f:/g/personal/jonathan_sanjuan_infor_com/Egah2tcRPNpIlEwQGmp704MByIiWyTJ8lnybPlBI1Whx_g?e=hx0gcY](url)

**Comment by jonathansanjuan** [comment]
Added fiddler log for Chrome
[https://inforonline-my.sharepoint.com/:u:/g/personal/jonathan_sanjuan_infor_com/EaEWrVa35gJDjioSREPVIggBNvH4zWfSRHOfca4DRFvoEQ?e=ogjMCN](url)

**Comment by anhallbe** [comment]
Confirmed. `IonApiService` does not work as expected when deployed in MT.

Thanks for the report, will fix ASAP.

**Comment by anhallbe** [comment]
A patch (2.1.2) has been released to solve the issue. Thank you for submitting the report!

**Comment by Amiin29** [comment]
> A patch (2.1.2) has been released to solve the issue. Thank you for submitting the report!



> Confirmed. `IonApiService` does not work as expected when deployed in MT.
> 
> Thanks for the report, will fix ASAP.

Hey my friend I have a question about the connection with server with the method rest api basic authentication help me please

**Comment by karinpb** [comment]
@Amiin29 Your comment does not seem related to this ticket. If not then please add a new ticket where you actually describe your issue. This issue is closed. There is no basic authentication support when calling ION APIs.

**Comment by Amiin29** [comment]
> @Amiin29 Your comment does not seem related to this ticket. If not then please add a new ticket where you actually describe your issue. This issue is closed. There is no basic authentication support when calling ION APIs.

I am in the process of developing a mobile application using ionic and angular for the purpose of devloping a task so my problem is connecting with the server and accessing the  CRS610MI / LstByNumber.
![Untitled](https://user-images.githubusercontent.com/67683686/112063558-e0878b00-8b61-11eb-84a4-e6490fd58ffa.png)

**Comment by Amiin29** [comment]
> 
> 
> @Amiin29 Your comment does not seem related to this ticket. If not then please add a new ticket where you actually describe your issue. This issue is closed. There is no basic authentication support when calling ION APIs.

![image](https://user-images.githubusercontent.com/67683686/112130049-558dab80-8bc8-11eb-91a3-d14d5da02ab7.png)
![image](https://user-images.githubusercontent.com/67683686/112130078-5d4d5000-8bc8-11eb-8a4f-1d3672481bdf.png)

**Comment by anhallbe** [comment]
Locking this issue, as the original problem was solved.

The additional problems described seem more related to web programming in general and ION API, for which there are other discussion/support forums.
