### ISSUE TITLE
calling m3 h5 standard IDM widget

### ISSUE THREAD

**Issue by dilankap** [infor-cloud/m3-h5-sdk#106]
## Description
how can you integrate standard m3 h5 IDM widget to h5 SDK ?

(Sample screen shot of m3 h5 IDM widget)
![image](https://user-images.githubusercontent.com/31741266/130577626-72bf8ce4-f2e4-4115-b125-cee54d6beddc.png)
![image](https://user-images.githubusercontent.com/31741266/130577684-684a62cf-5d9e-436b-b9cb-8362a7369a57.png)
 

## Versions
m3 h5 sdk v4.0

**Comment by anhallbe** [comment]
Hi!
I'm not sure I understand what you want to achieve. Could you ellaborate?

**Comment by dilankap** [comment]
Attached are the screenshots of the standard widget of the IDM upload in M3. 
my expectation is to associate the same with h5 SDK.

1. Is that possible ? 
2. what are the other alternatives ?

**Comment by anhallbe** [comment]
- If you want to run the IDM widget inside a H5 SDK application, then no, that is not possible.
- If you want to build your own UI that communicates with the IDM API:s, then yes that is possible.
- If you want to run a H5 SDK app inside a widget, then no. You should use the Homepages Widget SDK.
