### ISSUE TITLE
Can you retreive Tenant URL in the code ?

### ISSUE THREAD

**Issue by Messaoudi-Nagib** [infor-cloud/m3-h5-sdk#117]
## Description
Hi, I have to make a button that leads to infor M3 screen, I'm using drillback URL to do it, but depending on wich environment I work, I would like to get the right tenant URL.

Is that a way to do it ? (API, or other method ?)

Thank you, regards

## Versions
Infor M3 cloud

**Comment by premkumarparames** [comment]
Hi Messaoudi-Nagib, You can use the 'launch' method from the 'ApplicationService' service available in the framework to launch M3 programs, Bookmarks, and Mform Automation URL, it's equivalent to the Run command in M3. There is an example available in the sample app for the same for reference "https://github.com/infor-cloud/m3-h5-sdk/blob/master/m3-odin/src/app/soho-app/samples/launch/launch.component.ts"

**Comment by premkumarparames** [comment]
You can get the current session info including the tenant id from the m3 context grid endpoint "/grid/user". 
I believe we don't need the tenant id in the bookmark url, do you mind sharing what is it you trying to do, for example, are you trying to open an M3 program from the h5 application with certain fields to be filled in automatically or you are trying to launch another Infor OS application.

**Comment by Messaoudi-Nagib** [comment]
Ok ! thank you very much, yes I'm trying to open an M3 program from H5 application (mashup) so basically what I've done is :

- Get the drillback URL of the M3 screen I want by taking the URL from M3 contextual Menu for example 
`?LogicalId=lid://infor.m3.m3&program=OIS320&fieldNames=WWCUNO,999999,WWFACI,001,WWORNO,,WWPONR,,WWPOSX,,WWORTP,,WWNEPR,,WWCUCD,,WWWHLO,,WWPOPN,,WWITNO,,WWBANO,,WWORQA,,WWALUN,,WWPRDT,,WWSPUN,,WWSACD,&includeStartPanel=True&source=MForms&requirePanel=True&panel=B&tableName=OOI320&keys=OTCONO,600,OTCUNO,999999,OTITNO,,OTDWDT,+,OTQTLB,+,OTNETP,+,OTFVDT,+,OTDIPO,+,OTAGNO,+,OTAGLN,+,OTPRRF,+,OTPIDE,+&parameters=WWITNO, `
- Then in my code I build up the drillback URL with the rest of the URL just like that : 
`window.open("https://mingle-portal.eu1.inforcloudsuite.com/XXX/" + (drillback_URL)`

Do you think it is possible to open an M3 screen without the begining of the URL, if so, I would appreciate if you give me some advices.

Thank you, regards

**Comment by premkumarparames** [comment]
@Messaoudi-Nagib Your H5 application is already running within the M3 context, so you don't need the M3 URL or the mingle URL to launch an M3 program or the bookmark. You can pass the program name in the lanch method or the bookmark with the prefix "bookmark?" or the mform automation XML string with the prefix "mforms://_automation?data=<XML_String>".

For example,

-  this.applicationService.launch("OIS320"); //this will launch the OIS320 progarm in an application tab
- this.applicationService.launch("bookmark?program=OIS320&fieldNames=WWCUNO,,WWFACI,001,WWORNO,,WWPONR,,WWPOSX,,WWORTP,,WWNEPR,,WWCUCD,,WWWHLO,,WWPOPN,,WWITNO,,WWBANO,,WWORQA,,WWALUN,,WWPRDT,,WWSPUN,,WWSACD,&includeStartPanel=True&source=MForms&requirePanel=True&panel=B&tableName=OOI320&keys=OTCONO,600,OTCUNO,,OTITNO,,OTDWDT,+,OTQTLB,+,OTNETP,+,OTFVDT,+,OTDIPO,+,OTAGNO,+,OTAGLN,+,OTPRRF,+,OTPIDE,+&parameters=WWITNO,"); // launch the OIS320 program with the fields populated from the url parameters
- this.applicationService.launch("mforms://_automation?data=<?xml+version='1.0'+encoding='utf-8'?><sequence><step+command='RUN'+value='OIS320'+/><step+command='AUTOSET'><field+name='WWFACI'>001</field><field+name='WWCUNO'>1234</field></step></sequence>"); // similar to boomark but it can also automate some actions steps in the program 

 Hope this helps.

**Comment by Messaoudi-Nagib** [comment]
This is exactly what I want ! thank you so much for the answer !

Regards !
