### ISSUE TITLE
Issue with H5 SDK ION API request 

### ISSUE THREAD

**Issue by gmssyam** [infor-cloud/m3-h5-sdk#126]
Hi Team,

I am trying to use the demo sample that is present as part of SDK and when I am trying to use the sample I am getting following error:
****HTTP ERROR: 403 Forbidden
Problem accessing /mne/M3/m3api-rest/execute/MNS150/GetUserData;metadata=true;maxrecs=100;excludempty=false;returncols=CONO,DIVI,USID,NAME?_rid=HW6C68DOUB142A50**

JWT authentication disabled (error: 141)**

Request URL:
http://localhost:8080/m3api-rest/execute/MNS150/GetUserData;metadata=true;maxrecs=100;excludempty=false;returncols=CONO,DIVI,USID,NAME?_rid=HW6C68DOUB142A50

Params: HW6C68DOUB142A50
<img width="960" alt="Giterror" src="https://user-images.githubusercontent.com/103484362/162895367-540bb17e-4055-492b-bb66-87093d2a6acf.png">

Can you please help me with any other configuration needs to be changed etc..

**Comment by swuendri** [comment]
Hello @gmssyam,

can you describe the steps to reproduce your error (sequence of odin commands)?

**Comment by gmssyam** [comment]
Hello @swuendri ,

I have created new application using odin new, selected Angular, Soho Design.

Then I have set up proxy with ION API URL as per: https://github.com/infor-cloud/m3-h5-sdk/issues/55#issuecomment-651713612
Then ran odin login ./path/to/downloaded-file.ionapi  , odin serve --multi-tenant --ion-api

CRSF token is getting generated but user context method ( mns150  API) is getting 403 error with above details shared.

I am not sure it is the issue with ION API or set up or tenant url configuration


Thanks in advance,
Syam

**Comment by swuendri** [comment]
Hello @gmssyam ,

do not setup odin.json manually please. Instead use `odin login` for the first time with option `-c` or `--update-config` like `odin login -c ./path/to/downloaded-file.ionapi` to put the right things to odin.json. Afterwards `odin serve --multi-tenant --ion-api` should be successfully run.

**Comment by gmssyam** [comment]
Okay thank @swuendri it worked.

**Comment by swuendri** [comment]
Great @gmssyam, please close the issue finally.

**Comment by gmssyam** [comment]
resolved
