### ISSUE TITLE
Next release build

### ISSUE THREAD

**Issue by ftunholm** [infor-cloud/m3-h5-sdk#142]
## Description
When will there be a release build available that includes the following commit: d1e205e43762833b7350d1d9e76396550a40acf9? We have issues with the build command and compability with Angular 14. I solved it manually for now.

**Comment by anhallbe** [comment]
There is a `6.0.0-next.2` pre-release out with Angular 14. (See instructions here: https://github.com/infor-cloud/m3-h5-sdk/issues/129#issuecomment-1193143910)

A stable `6.0.0` with better instructions etc should be ready Soon™

**Comment by anhallbe** [comment]
6.0.0 is now released! See [CHANGELOG](https://github.com/infor-cloud/m3-h5-sdk/blob/master/CHANGELOG.md)
