### ISSUE TITLE
CORS error response from IonApiService

### ISSUE THREAD

**Issue by anhallbe** [infor-cloud/m3-h5-sdk#18]
**Describe the bug**
The ION API server returns an error when sending POST-requests through the IonApiService during development (`odin serve`).

The server responds with a status 400, and the body:
```json
{
  "error": "CORS error - Origin is invalid"
}
```

**To Reproduce**
Call `IonApiService.execute()` like so:

```typescript
this.ionApiService.execute({
  method: 'post',
  url: 'some/api/path',
  responseType: 'json',
  source: 'something',
}).subscribe(
  () => log("success"),
  () => log("error"),
)
```
When this is executed, "error" is logged.

**Expected behavior**
The above code should log "success".

**Version**
 - `@infor-up/m3-odin`: 2.1.2
 - `@infor-up/m3-odin-angular`: 2.1.2
 - `@infor-up/m3-odin-cli`: 2.1.2

**Comment by anhallbe** [comment]
**Update:** It seems like the ION API service rejects requests from origins with `http://`. A workaround (until a fix is added to the CLI) is to add the Origin header in `odin.json`:

```json
    "/ODIN_DEV_TENANT": {
      "target": "https://ionapi-server-address",
      "secure": false,
      "headers": {
        "Origin": "https://localhost"
      },
      "changeOrigin": true,
      "pathRewrite": {
        "^/ODIN_DEV_TENANT": "/MY_TENANT"
      },
      "logLevel": "debug"
    }
```

**Comment by kakaluto** [comment]
Hi Andreas,
I've tried your solution. Using this configuration still starts on localhost:8080 and not in https mode.
I've tried using ng serve --ssl true
This starts in https mode but now i have this error message :
https://mingle-***************.com/******************/M3/m3api-rest/execute/MMS200MI/LstItmByItm?CONO=100&ITNO=%20 401 (Unauthorized)

in the header i've got : 
POST https://mingle-********/*********/M3/m3api-rest/execute/MMS200MI/LstItmByItm?CONO=100&ITNO=%20 HTTP/1.1
Host: mingle-***********.com
Connection: keep-alive
Content-Length: 0
Accept: application/json, text/plain, */*
Sec-Fetch-Dest: empty
Authorization: Bearer t+fKKyhnG99LejoYFUq0fhDo5Zt+1LhpTnAPFheTpnUsmohcayfgFMQyVp4cVuTdVGRq1VqgSbVRVxdOL0afhYlSjUN/OetSXxpe3DDg7IEV4NcGuF/YGkTJiS10zBnxCnzNELB8VLNkvgqvYuYiuL/4J/8NjNu3Oqxk9yL0IO562oPA7s6J7AOKz/Th5GqmZixncizHk/NfGcJwoqaZzmr2VU4q4XVXcY+U09XYtOy5/T8snRkzjfnJs3IJQ3c9dpIokTUNH4bm32OZLjJoVBcqAtRnBrAHIjKAm1rY1sbno7YbkqR4N3j5CoXBBK1ee/8TN9/mFGneYWeQAE3WXw==
x-infor-ionapi-platform: m3-odin
x-infor-ionapi-source: m3-odin-https://localhost
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Origin: https://localhost:4200
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Referer: https://localhost:4200/
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: opentoken_cookie=eyJraWQiOiJuaiIsImFsZyI6IkVTMjU2In0.eyJPcGVuVG9rZW5WYWx1ZSI6IlQxUkxBUUdYc3dXZjAyUW00QlYwRDdfZ2J1S3V3QWF5MmhBU2RxTDQxb2VfczFweHRGUWMyZkdOQUFHd01JMW5vZlh4UF9fSHRXWmUxblpLUThTd01JeC1xX1JaaFloX0Jlakt0QmlFYlhLWE5MS2NBdG05N1l4eUhweE1Bb1pKMl90SVZtN0pLWUhXUjdaVHlBazZVcTR4enB5VGEwajh3SEZOMHJGOXMwcENxRHBkZFl5VUtkdXhUV0V5bWxmZlhIQk9EdnE0d2Mxam5WS3RGVElKeTQ5VEs2NlViazlrdENXTUcxTGVobzdGRXhLY1pRc1JZaE9uTHBfS0RZN3d3YmROUmhnQ3pVcDFWNTdFeDh1ZGV6MWdZZm1qUVdEeGNxWjJiYUk4RndUcUVWYzZHLUtvWDlVZ3Zza25oYkU5RnN0cWNvUzI1aGNfdV81V1cwOThLUnE4OW9jQ19QajBSR3pEcWUtNmZjcDV1cDVBQ2hmVHVRMkFZOEMtV0JYZ1pqckg2Nl9PWU1PcUJiTGExaU1kSE43UHV4TGFOR3M4VlVwbmxha0xUSkJZM1pzQ1AwOG9tRUx6N0QtcWZQWm56VW9mSGd0dGJtRnFEN0tCN3Vqc0JMRmljc0o0UFJRT0IxRFhULWJPaG14aVpkYzE4NzMxMzlZOXVKTlE4LVcwYlZaTTZsakJqLUhfTld5amJaMVBoMGswalBKRDIxVjhZQ2hXaHhUUjNQdFluMGN3QlA4RjhXcVVmSENxbDBXZlJwaDFKY1VnWU5wTHBQemtrM0c5eHhqeG91ZjZtNXlCNFc1UVR2RUtUY3Q4bVZMemJnMnQzSVAwejFVOCIsIlRva2VuVmVyc2lvbiI6InYyIn0.CzyEIWaKoORb-ZW57SnvHc2d1pJZkRWNOrhEhzxffZA-InforMingle; grid-sid-a1854c001dcf5147=ni2QzV2C+3V6ygrCEYhZDcGEsHHcsjG/C6wD1kSTBv8=; grid-sid-acaad696b7bfaa4b=my+PIU5KYFDXn74Kbtg5PNoemibduzeU8opl340UBv8=; PortalCulture_lttdconsulting_dem=language=fr-FR&locale=fr-FR&timezone=Europe/Berlin; CollaborationEnvCookie=logicalid=lid%3A%2F%2Finfor.social.1&current_language=fr-FR&current_locale=fr-FR&current_timezoneId=W.%20Europe%20Standard%20Time; useractivity_cookie_mingle=1581339208


I'am in dev mode and try to call an api using ion apis. 
Do you have any idea of what is wrong?

Thanks

**Comment by alliancehaydenm** [comment]
Hi there - having the same issue in Odin 2.2.1, Angular 7. Have tried the above workaround. 
![image](https://user-images.githubusercontent.com/62520530/79830953-9ef2db00-83fa-11ea-9a86-c4c169de532c.png)



I'm trying to call an ION datalake API at this endpoint. Any advice?
https://mingle-ionapi.se2.inforcloudsuite.com/ALLIANCEGRP_DEV/IONSERVICES/datalakeapi/v1/compass/jobs?resultFormat=text/csv

Error:
Access to XMLHttpRequest at 'https://mingle-ionapi.se2.inforcloudsuite.com/ALLIANCEGRP_DEV/IONSERVICES/datalakeapi/v1/compass/jobs?resultFormat=text/csv' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. [http://localhost:8080/]

![image](https://user-images.githubusercontent.com/62520530/79830855-63f0a780-83fa-11ea-875d-a29e28a58c60.png)

**Comment by anhallbe** [comment]
A fix has been added in version `3.0.0-next.4`.

**Comment by Amiin29** [comment]
> Hi there - having the same issue in Odin 2.2.1, Angular 7. Have tried the above workaround.
> ![image](https://user-images.githubusercontent.com/62520530/79830953-9ef2db00-83fa-11ea-9a86-c4c169de532c.png)
> 
> I'm trying to call an ION datalake API at this endpoint. Any advice?
> https://mingle-ionapi.se2.inforcloudsuite.com/ALLIANCEGRP_DEV/IONSERVICES/datalakeapi/v1/compass/jobs?resultFormat=text/csv
> 
> Error:
> Access to XMLHttpRequest at 'https://mingle-ionapi.se2.inforcloudsuite.com/ALLIANCEGRP_DEV/IONSERVICES/datalakeapi/v1/compass/jobs?resultFormat=text/csv' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. [http://localhost:8080/]
> 

Hi guys you have an idea to make a configuration on m3 w to enable the url because i have the same issue and I think the revolution of this problem is this idea

**Comment by Amiin29** [comment]
Hi guys you have an idea to make a configuration on m3 w to enable the url or  I let CORS desable to give access to all the url  because i have the same issue and I think the revolution of this problem is this idea

**Comment by karinpb** [comment]
@Amiin29 Please stop commenting on tickets that are closed. Follow the documentation and samples to get started. You cannot call any endpoint directly in development, you need to use the proxy. What I can see from previous comments you are trying to call the M3 rest directly, it will never work. Take the latest version, use the proxy and if you find an issue be sure that you are following the samples and then create a ticket with a lot of information about all the steps that you have taken.

**Comment by Amiin29** [comment]
> use the proxy and if you find an issue be sure that you are following the samples and then create a ticket with a lot of information about all the steps that you have taken.

thank you for your answer it is running correctly

**Comment by Amiin29** [comment]
> > use the proxy and if you find an issue be sure that you are following the samples and then create a ticket with a lot of information about all the steps that you have taken.
> 
> thank you for your answer it is running correctly
and I apologize because I comment on the tickets that are closed
