### ISSUE TITLE
Prb with sample project / angular material / angular 8.2.1

### ISSUE THREAD

**Issue by HeikoDE** [infor-cloud/m3-h5-sdk#20]
Hi,

Angular 7 was installed with the SDK, but I needed to update to Angular 8 to be compatible with other downloaded code and its dependencies. Everything works fine with the Odin/SoHo sample, but with the Odin/Material sample 'odin serve' refuses to start, showing the following errror:

"Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
... ... ..."

Any hints? Something which needs to be updated ?

best regards
Heiko

**Comment by anhallbe** [comment]
A new version is on the way with updated dependencies.

See https://github.com/infor-cloud/m3-h5-sdk/releases/tag/v3.0.0-next.1
