### ISSUE TITLE
Is there a message service to show messages like in infor M3

### ISSUE THREAD

**Issue by hldarshana** [infor-cloud/m3-h5-sdk#21]
## Description
Does this library support showing messages in a bottom panel like in Infor M3 ?

![messages](https://user-images.githubusercontent.com/60569119/73606960-212aea80-45d6-11ea-91b2-f3ec1451029e.JPG)

**Comment by anhallbe** [comment]
The SDK itself does not contain such a UI component. But you could implement something similar using IDS Toasts, or something of your own. It sort of depends on the use-case and what kind of features you want (duration to show messages, delete individual messages, scrolling, clearing etc).

https://anhallbe.github.io/enterprise-ng/toast
https://github.com/infor-design/enterprise-ng/blob/master/src/app/toast/toast.demo.ts
