### ISSUE TITLE
how to use IDS tags 

### ISSUE THREAD

**Issue by SindhuraPaleru** [infor-cloud/m3-h5-sdk#210]
Hello Team,

I am new to using ids tags in h5 sdk. I just installed a sample project(odin new) with Angular framework and SoHo style library.
I tried to use ids tags in the html page but its throwing an error as shown below:
<img width="629" alt="2024-11-27_15h33_57" src="https://github.com/user-attachments/assets/6e245f29-db8b-4eac-8df3-f72ddae0b95d">

Can someone please help me to understand how to fix this and use ids tags?

**Comment by SindhuraPaleru** [comment]
@karinpb Any suggestions on resolving my issue! Please advise.

**Comment by SindhuraPaleru** [comment]
@anhallbe  Any suggestions on resolving my issue! Please advise.

**Comment by anhallbe** [comment]
Assuming you want to use the IDS web components, you'll need to install it first:

https://www.npmjs.com/package/ids-enterprise-wc

See the [repo](https://oxford.awsdev.infor.com/infor-design/enterprise-wc) for documentation, samples etc

**Comment by tmcconechy** [comment]
@SindhuraPaleru Try looking at this example project https://oxford.awsdev.infor.com/infor-design/enterprise-wc-examples/-/tree/main/angular-ids-wc?ref_type=heads

If you dont have an Infor Id ask your sponsor if a partner.

You are probably missing CUSTOM_ELEMENTS_SCHEMA pasting the docs here for you

```md
# Ids Web Components with Angular

Ids Web Components use custom elements and have a typescript definition so can work in angular without a wrapper. Use the following steps to consume a ids web component in a simple angular project. This project was created with [angular cli](https://angular.io/cli).

1. Add `ids-enterprise-wc` with `npm install ids-enterprise-wc -D`
1. Added imports to `src/app/app.component.ts`, you can either import every component via the `enterprise-wc.js` file. Or a better method is to list each components you actually use as individual imports

```js
// ALL
import 'ids-enterprise-wc/enterprise-wc.js';

// OR 
import 'ids-enterprise-wc/components/ids-tag/ids-tag';
import 'ids-enterprise-wc/components/ids-alert/ids-alert';
```

1. Note that all imports also include the contained css styles so no style sheets are needed
1. Note that using imports in the angular.json is not currently possible for ES Modules https://github.com/angular/angular-cli/issues/24592
1. Since we ship our package as Es Modules (ESM) the best way to use the components is to import the used modules (or complete package) inside the module where its used. For example:
1. Add `skipLibCheck` so that the types in the node_modules are not checked. This may be needed if using a different TS version that the one we compiled with and you experience compile errors. https://oxford.awsdev.infor.com/infor-design/enterprise-wc-examples/-/blob/main/angular-ids-wc/tsconfig.json?ref_type=heads#L18

```js
import { Component, OnInit } from '@angular/core';
// Import used components
import 'ids-enterprise-wc/components/ids-alert/ids-alert';

@Component({
  selector: 'app-example',
  templateUrl: './example.component.html',
  styleUrls: ['./example.component.css']
})
export class ExampleComponent implements OnInit {
  constructor() { }
  ngOnInit(): void {
  }
}
```

If the module is being used in the code you can change the import as follows and invoke it if needed.

```js
import { Component, AfterViewInit} from '@angular/core';
import { routes } from './ids-tag-routing.module';
import IdsTag from 'ids-enterprise-wc/components/ids-tag/ids-tag';

@Component({
  selector: 'app-ids-tag',
  templateUrl: './ids-tag.component.html',
  styleUrls: ['./ids-tag.component.css']
})
export class IdsTagComponent implements AfterViewInit {
  public routes = routes.filter(r => r.path !== '');

  constructor() { }

  ngAfterViewInit(): void {
    console.log('Ids Tag init');
    const dynamicTag = new IdsTag()
    dynamicTag.textContent = 'Dynamic';
    document.body.append(dynamicTag);
  }
}
```

1. Add `CUSTOM_ELEMENTS_SCHEMA` to `src/app/app.module.ts`
1. The localization data and translations are fetched dynamically in the IDS code when a locale is set. In order to change language you will need to serve the locales. To do this we add a location to the assets section in `angular.json`.

```json
"assets": [
  {
    "glob": "**/*",
    "input": "./node_modules/ids-enterprise-wc/locale-data",
    "output": "/locale-data"
  }
],
```
1. The themes are fetched dynamically in the IDS code when a theme is set with the theme switcher. In order to change theme you will need to serve the theme css files. To do this we add a location to the assets section in `angular.json`.

```json
"assets": [
  {
    "glob": "**/*",
    "input": "./node_modules/ids-enterprise-wc/themes",
    "output": "themes"
  }
],
```
1. Add the font to index.html 
```html
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600&amp;display=swap" rel="stylesheet">
```
1. `npm run start`
1. If wanted you can shorten the import paths using this feature https://blog.bitsrc.io/short-typescript-import-paths-in-angular9-22ce34bd424d 
1. If you wanted to you can also speed up the builds with es-build you  could https://www.danywalls.com/maximizing-your-angular-build-performance-with-esbuild

```

**Comment by SindhuraPaleru** [comment]
@tmcconechy 
It helped! Thank you so much
