### ISSUE TITLE
Can we use IonApiService in production environment?

### ISSUE THREAD

**Issue by hldarshana** [infor-cloud/m3-h5-sdk#24]
Hi,

We are using m3-odin 2.1.0 with angular 7 to build an infor M3 application. 

The IonApiService execute requests successfully in local development environment. However after install the application in infor M3, it fails to execute. Seems it is trying to authenticate and fails.

![image](https://user-images.githubusercontent.com/60569119/75147140-ae1f1a80-5722-11ea-95a5-7b088361e90e.png)

Could you explain how IonApiService can be used in production environment?

**Comment by anhallbe** [comment]
@hldarshana is this the same issue as https://github.com/infor-cloud/m3-h5-sdk/issues/10?

A fix was added for that one in 2.1.2

**Comment by hldarshana** [comment]
@anhallbe  works fine after upgraded to 2.1.2

Thanks
