### ISSUE TITLE
Using miservice / ionService on-prem and in cloud

### ISSUE THREAD

**Issue by mbenmoussati** [infor-cloud/m3-h5-sdk#25]
## Description
Hi,
Do we have to change all our on-premise H5 mashups (which are using miservice) to use IonApiService when we deploy them to multi-tenant envs?
When i deploy one of my mashups to multi-tenant, this mashup works. So why do we have to pass by ionApi since it works with miService?

Thanks.

**Comment by karinpb** [comment]
No, you don't have to change to use IonApiSerice for MI calls. The ION API must be used for anything else that you might want to call, like Infor Document Management, ION etc. There is no requirement to only call through IONAPI at this time, but that might change in the future.

There is support coming for CSRF (https://en.wikipedia.org/wiki/Cross-site_request_forgery) and for that we will update the M3 H5 SDK. With that code in place it should still be possible to build once and deploy on-prem and in cloud. When we built the multi-tenant proxy tool the focus was not only on MI, but also on all other calls that you can make. ION API has a lot of advantages in terms of viewing the request logs etc that you might want to have in a cloud environment.

**Comment by karinpb** [comment]
Re-open since I've changed the answer and is waiting for more information. This is basically a policy decision. Either way MI calls will need to support CSRF tokens in September for MT. Calling in MT through ION API will always work, but the focus we had when building the proxy was to allow calls to other applications like IDM and Social. When you execute the application you are in H5 and it's a H5 app.

**Comment by SindhuraPaleru** [comment]
Hello Karin! 

Between MIService and IONAPIService, what do you suggest is the best way to call an infor m3 api in h5 scripting in multi tenant?

**Comment by karinpb** [comment]
I would use MIService in a H5 Script.

**Comment by SindhuraPaleru** [comment]
Okay! Thanks for your quick response, Karin.
I have seen two ways of using MIService, One is execute and the other is executeRequsest. Which of the following is valid in Multi Tenant or Are they both equally valid?
1) MIService.Current.execute(program, transaction, record, outputFields)
2)MIService.Current.executeRequest(MIRequest_Object)

**Comment by karinpb** [comment]
Both are valid.
