### ISSUE TITLE
Using IonApiService in a single-tenant environment

### ISSUE THREAD

**Issue by olivergalleguez** [infor-cloud/m3-h5-sdk#26]
## Description
Hi, we're trying to use IonApiService to call Ming.le APIs but we're having this error (screenshot below). It seems like it's trying to get the OAuth token but is failing because the endpoint does not exist. Is there something that needs to be set up before calling APIs through ION?

![image](https://user-images.githubusercontent.com/4433917/75440471-cb5c1f00-5996-11ea-9cf0-d55f387e3405.png)

Mingle API is already installed in the environment and we were able to test those, but when we tried to call those in our SDK app it fails

![image](https://user-images.githubusercontent.com/4433917/75441175-217d9200-5998-11ea-8e5a-31b135c7e1c2.png)

## Versions
- MUA: 10.3.1.0.437
- Angular: 7.1.0
- @infor-up/m3-odin: 2.1.2
- @infor-up/m3-odin-angular: 2.1.2

**Comment by karinpb** [comment]
Hi,
I’m afraid that MUA: 10.3.1.0.437 does not have support for getting the OAuth Token. Or actually it’s the Infor ION grid that is 1.13 for that version and the endpoint is only available in Infor ION grid 2.0 (which is used in Cloud).   It’s new functionality and the grid team said that they could not push it to 1.13 and the M3 team run M3 on  the 1.13 version of the grid on-prem, so it’s not supported and there is no work-around. If you want to address this to support, as an enhancement request, it should be directed to M3. I’m sorry but new functionality comes in newer versions of the software, and it’s not always possible to add it to the existing version. This is such a case. For IDM there is a proxy so calling IDM is supported, but there is no way to call an ION API unless you are running on an Infor ION Grid version 2.0.
