### ISSUE TITLE
Is there anyway to open a m3 program programatically?

### ISSUE THREAD

**Issue by ErrorCode101** [infor-cloud/m3-h5-sdk#28]
## Description
Hi,

We are using m3-odin 2.1.2 with angular 7 to build an infor M3 application. 

We want to open  CRS610 program on a button click  in a new panel instead of a new browser tab. We tried to use formService.executeBookmark method but it returns a result type of IFormResponse which is not the required output. Is there anyway to open a bookmark or program with parameters in a new m3 panel.

**Comment by karinpb** [comment]
Hi,
I'm not sure what you mean with a new browser tab. The program should run in H5 so it will open in a H5 tab. You launch programs bookmarks ets with ApplicationService.launch(bookmarkURL). Check out and test with the launch example.

For example with a string like this:
`mforms://bookmark/?program=CRS610&tablename=OCUSMA&keys=OKCONO%2c136%2cOKCUNO%2cMANGO%2b%2b%2b%2b%2b&option=2&panel=E&name=Customer.+Open+-+CRS610%2fE&source=MForms`.

If you would like the CRS610 program inline in a panel then you need to build a custom UI for it using the form service and the data that is returned. I would not recommend that.

Hosting the entire program in an iframe or similar is not supported. It might be possible to host a Mashup, if there is an example for it. @anhallbe Do we have any example hosting a Mashup?

**Comment by ErrorCode101** [comment]
Hi we figured this after few tries.. Thank You!.. ..
