### ISSUE TITLE
CSRF_INVALID_SESSION when proxying MI requests to ION API

### ISSUE THREAD

**Issue by anhallbe** [infor-cloud/m3-h5-sdk#30]
**Describe the bug**
When the development proxy is forwarding /m3api-rest requests to an ION API endpoint, it is also forwarding the `fnd-csrf-token header`. The ION API gateway (or M3?) rejects these requests with an error `CSRF_INVALID_SESSION`.

**To Reproduce**
GIVEN: An application that attempts to make a request using the `MIService` or `UserService`.

1. Launch the MT Login tool with the "Verbose Login" script, and configure it to use ION API.
2. Start the odin dev proxy with `odin serve -m`
3. Start the application in the browser, so that it triggers the request.
4. A CSRF request is successfully sent, followed by a failed API request.

**Expected behavior**
A CSRF token request is sent successfully, followed by a successful /m3api-rest.

**Version**
 - `@infor-up/m3-odin`: 2.2.0
 - `@infor-up/m3-odin-angular`: 2.2.0
 - `@infor-up/m3-odin-cli`: 2.2.0

**Additional context**
The problem only occurs when proxying requests to ION API. Launching the "M3 Only Login" script followed by `odin serve -m` works fine. The problem is that the proxy incorrectly forwards the `fnd-csrf-token` header to ION API, even though it is not needed.

**Comment by DXCdhenningsver** [comment]
What is the status of this bug? Is there any workaround except running version 2.1.0?

**Comment by anhallbe** [comment]
@DXCdhenningsver you wan work around it by proxying requests directly to M3 instead of through ION API. I.e run the MT Login tool with "M3 Only Login" and then `odin serve -m`.

**Comment by DXCdhenningsver** [comment]
I also got it working by adding the parameter enableCsrf: false to the IMIRequest

**Comment by anhallbe** [comment]
This has been fixed in `3.0.0-next.2`.

**Comment by anhallbe** [comment]
Fixed in version 3
