### ISSUE TITLE
Is that possible to launch the H5 sdk app as a Infor OS widget?

### ISSUE THREAD

**Issue by Xiang-Ji615** [infor-cloud/m3-h5-sdk#34]
## Description
Can I pls ask if that's possible to launch the H5 sdk app as a Infor OS widget?
Thx in advance.

**Comment by karinpb** [comment]
It's possible to enter a URL for a Homepages widget, so yes it's possible.
If you are meaning Contextual Applications in Mingle, those can also be a URL so yes it's possible.
