### ISSUE TITLE
Soho Datagrid: Paging number are showing placeholder instead of actual values

### ISSUE THREAD

**Issue by B150yin** [infor-cloud/m3-h5-sdk#35]
**Description**
Datagrid `paging` and `showPageSizeSelector` options are set to `true` however the page number doesn't display the correct paging value. The page number is showing a placeholder "[PageOf]" and the page size selector is showing "[RecordPerPage]".

**To Reproduce**
1. Use the infor-m3-odin-sample-soho-2.2.1 as example: 
[infor-m3-odin-sample-soho-2.2.1.zip](https://github.com/infor-design/enterprise-ng/files/4442455/infor-m3-odin-sample-soho-2.2.1.zip)
2. Click on Customer tab (page number and  fine)
3. Refresh the browser
4. The page number and page size selector became placeholder.
(If click on another tab and back to customer tab, the page number is working fine again)

**Expected behavior**
Paging number and page size selector should be same as the screenshot below:
![image](https://user-images.githubusercontent.com/36392515/78639576-ce74f400-78e0-11ea-8671-10c8338f79ec.png)

**Version**
- ids-enterprise-ng: v5.0.0
- infor-up/m3-odin: v2.2.1
- infor-up/m3-odin-angular: v2.2.1

**Screenshots**
![image](https://user-images.githubusercontent.com/36392515/78639499-a4233680-78e0-11ea-906d-5c4266b04716.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 80.0.3987.163 (Official Build) (64-bit)

**Additional context**
I would like to use a datagrid be the first page of my application.

**Comment by anhallbe** [comment]
Fixed in 3.0.0
