### ISSUE TITLE
retrieving UserContext on CE multitenant env

### ISSUE THREAD

**Issue by mbenmoussati** [infor-cloud/m3-h5-sdk#36]
Hi @anhallbe @karinpb .

## description : 

I always got an error with userService. It is related to the but retrieved by @anhallbe with the CSRF
My log :
UserService {logPrefix: "[UserService] ", instance: UserServiceCore}
logPrefix: "[UserService] "
instance: UserServiceCore
logPrefix: "[UserServiceCore] "
miService: MIService {logPrefix: "[MIService] ", instance: MIServiceCore}
isUserContextAvailable: true
queue: []
isExecuting: false
isMessagePending: false
userContext: UserContext
numberFormatOptions: {separator: "."}
errorMessage: "Failed to get CSRF token 500"
proto: ErrorState
proto: CoreBase
proto: CoreBase

Do you know how to bypass this error?

##Environment : 

Env : CE multitenant
Odin : 2.2.1
Service call :
this.userService.getUserContext().subscribe((userContext: IUserContext) => {
this.userContext = userContext;
}

thanks.

**Comment by anhallbe** [comment]
@mbenmoussati are you seeing any network errors? Check the network tab in the browser dev tools.

Also, does this error occur when running the dev server (`odin serve`), or in a deployed app?

**Comment by mbenmoussati** [comment]
> @mbenmoussati are you seeing any network errors? Check the network tab in the browser dev tools.
> 
> Also, does this error occur when running the dev server (`odin serve`), or in a deployed app?

Hi @anhallbe,
in the network tab i've got csrf : {error: "Server Error"}
error: "Server Error"

I'm running dev server on multitenant env.
Thanks

**Comment by anhallbe** [comment]
@mbenmoussati what does your `odin.json` look like, and what options are you providing to `odin serve`?

**Comment by mbenmoussati** [comment]
Hi @anhallbe ,
I've added some screenshot in the linked file : 
[Infor_H5_SDK_Issue#36.docx](https://github.com/infor-cloud/m3-h5-sdk/files/4677582/Infor_H5_SDK_Issue.36.docx)

Regards

**Comment by anhallbe** [comment]
Try `odin serve --multi-tenant --ion-api`.

**Comment by mbenmoussati** [comment]
@anhallbe : magician!!
it works!!! thanks a lot!!!!

**Comment by anhallbe** [comment]
I'm glad it worked out!

The cli documentation is lacking. Will fix
