### ISSUE TITLE
Call ION API or non-M3 endpoint from H5 SDK

### ISSUE THREAD

**Issue by alliancehaydenm** [infor-cloud/m3-h5-sdk#41]
## Description
I am attempting to call the ION datalake compass API from H5 SDK. No documentation on syntax or what are the common methods calling non-MI API's from M3.

Please advise what is the best way to do so.

Using standard user context API's to confirm login, etc. My user account has datalake permissions already.

## Versions
Odin 2.2.1, M3CE multi-tenant

**Comment by karinpb** [comment]
Hi,
I assume you would like to call Data Lake through ION API. Once available you'll find the Swagger API for the Data Lake API available in the ION API Application in Ming.le. This question is out of scope for the H5 SDK.

As for common methods you should have a look at the samples and specifically ion-api social, on how to call an ION API endpoint. But whatever data and URL needs to be passed is up to Data Lake.

` private loadUser(): void {
      const request = this.createRequest('User/Detail');
      this.ionApiService.execute(request).subscribe((response: IIonApiResponse) => {
         if (!response.body.ErrorList) {
            this.updateUser(response.body as IUserDetailResponse);
         }
         // TODO Error
      }, (response: IIonApiResponse) => {
         // TODO Error
      });
   }

   private createRequest(relativeUrl: string, headers?: object): IIonApiRequest {
      if (!headers) {
         // Create default headers
         headers = { Accept: 'application/json' };
      }

      // Create the relative URL to the ION API
      const url = this.serviceUrl + '/' + relativeUrl;

      // Create HTTP GET request object
      const request: IIonApiRequest = {
         method: 'GET',
         url: url,
         headers: headers,
         source: this.source
      };

      return request;
   }`

As for specific examples for the Data Lake API I don't have that. Have you tried with the [Infor Community - Data lake](https://community.inforxtreme.com/infor-ion/f/infor-data-lake)?
[welcome-to-the-data-lake-forum](https://community.inforxtreme.com/infor-ion/f/infor-data-lake/10292/welcome-to-the-data-lake-forum)

The H5 SDK provides the service that you can use to call ION API. Note that there is no need to check login as you will not be able to load the application without being logged in, if you deploy it in M3 H5. The token to call ION API will only be be available for logged in users.

 Security needs to be checked by the backend and not the client so unless you need user information there is no need to use the usercontext service to get user information.

**Comment by karinpb** [comment]
Infor ION Development Guide–Cloud Edition https://docs.infor.com/ion/12.0.x/en-us/ioncedg/default.html

**Comment by alliancehaydenm** [comment]
Hi Karen,

Thanks for the response - I can already use ION API & in fact Postman to call the Datalake API's with a SQL query. I would like to embed my query into an SDK web app so I can serve the query results to end users in a custom web interface in M3.

I'm calling the API correctly - I think - but am blocked in development/localhost by a CORS error. I see there's an old thread open for this, which I've commented on also.
![image](https://user-images.githubusercontent.com/62520530/79916977-c048db00-847d-11ea-8dbb-b4e4605a3da2.png)

Any advice on where to go with respect to building a web app in H5 that can achieve this Datalake API call?

**Comment by anhallbe** [comment]
Hi @alliancehaydenm !
Could you post a snippet of the code you wrote to produce the CORS error?

Are you using the `IonApiService` to do this?

[Here](https://github.com/infor-cloud/m3-h5-sdk/blob/master/m3-odin/src/app/soho-app/samples/ionapi-social/ionapi-social.component.ts)'s an example on how to perform ION API requests.

**Comment by alliancehaydenm** [comment]
Hi there! Here's my typescript for the API call:

private serviceUrl = 'https://mingle-ionapi.se2.inforcloudsuite.com/ALLIANCEGRP_DEV/IONSERVICES';


   private createRequest(relativeUrl: string, headers?: object): IIonApiRequest {
      if (!headers) {
         headers = { Accept: 'text/csv' };
      }

      const request: IIonApiRequest = {
         method: 'POST',
         url: this.serviceUrl + '/' + relativeUrl,
         headers: headers,
         body: this.query,
         source: this.source
      };

      return request;
   }

   onClickHTTP(): void {
      this.logInfo('onClickHTTP');
      this.setBusy(true);

      const request = this.createRequest('datalakeapi/v1/compass/jobs?resultFormat=text/csv');
      console.log(request.url);

      this.ionApiService.execute(request).subscribe((response: IIonApiResponse) => {
         if (!response.body.ErrorList) {
            console.log(response.body);
         }
         this.setBusy(false);
         console.log(response.body);

      }, (response: IIonApiResponse) => {
         this.setBusy(false);
         console.log(response.body);
      });
   }

**Comment by karinpb** [comment]
You have the URL hard coded in your sample so when you run this the browser will not allow it. You should be using the built in proxy. Only set the subpath to the service in ION API. Eg remove the service URL completely.

With the proxy you would be calling local host instead and the browser would allow it (at least Chome with security features off).

Make sure that the proxy is running and configured correctly. Check the documentation for more instructions. You cannot call the service with a full URL.

**Comment by rmonchery** [comment]
Hi, I am running into an issue similar to an issue where the web service I am calling is not receiving the data I am sending. Here's a snippet of the code I am using.
var request = {
            url: IonApiService.Current.getBaseUrl() + "/" + _this.mingleEndpoint + "/SocialService.Svc/User/" + _this.userGUID + "/ColleagueFeeds/" + colleagueUserGUID,
            method: "POST",
                data: { 
                    "Message": "thisMessage"
            }
        };
        IonApiService.Current.execute(request).then(function(response) {
            if (!response.data.ErrorList) {
                console.log("---------------SUCCESS------------------");
                console.log(response);
            }
            else {
                for (var _i = 0, _a = response.data.ErrorList; _i < _a.length; _i++) {
                    var error = _a[_i];
                    console.log("ERROR");
                    console.log(error.Message);
                }
            }
        })

**Comment by alliancehaydenm** [comment]
> You have the URL hard coded in your sample so when you run this the browser will not allow it. You should be using the built in proxy. Only set the subpath to the service in ION API. Eg remove the service URL completely.
> 
> With the proxy you would be calling local host instead and the browser would allow it (at least Chome with security features off).
> 
> Make sure that the proxy is running and configured correctly. Check the documentation for more instructions. You cannot call the service with a full URL.

Thanks for the reply Karin. 

private createRequest(relativeUrl: string, headers?: object): IIonApiRequest {

      if (!headers) {
         headers = { Accept: 'text/csv' };
      }

      const request: IIonApiRequest = {
         method: 'POST',
         url: relativeUrl,
         headers: headers,
         body: this.query,
         source: this.source
      };

      return request;
   }

   onClickHTTP(): void {
      this.logInfo('onClickHTTP');
      this.setBusy(true);

      const request = this.createRequest('/datalakeapi/v1/compass/jobs?resultFormat=text/csv');
      console.log(request.url);

      this.ionApiService.execute(request).subscribe((response: IIonApiResponse) => {
         if (!response.body.ErrorList) {
            console.log(response.body);
         }
         this.setBusy(false);
         console.log(response.body);

      }, (response: IIonApiResponse) => {
         this.setBusy(false);
         console.log(response.body);
      });
   }


I'm now getting a 404 - so presumably my proxy is not set correctly?
![image](https://user-images.githubusercontent.com/62520530/80151367-092f9980-860e-11ea-83fc-7a3a3b1822ca.png)

**Comment by anhallbe** [comment]
You should not include the application in the "target". Remove "IONSERVICES" from the proxy config "target" property.

**Comment by alliancehaydenm** [comment]
Hi team, still struggling with this issue. Since the datalake is an ION product; I've made the assumption that pre-configured proxy settings will allow a connection here. I can call M3 apis; but not the datalake.

I am able to call datalake & compass API's using other DEV tools such as Postman.

Is there an example code snippet available? The sample code packaged with the sdk does not prove useful in the context of datalake.

**Comment by anhallbe** [comment]
@alliancehaydenm the [ION API sample](https://github.com/infor-cloud/m3-h5-sdk/blob/master/m3-odin/src/app/soho-app/samples/ionapi-social/ionapi-social.component.ts) should be enough for any ION API request, including datalake.

I'm not sure how the datalake API works, but you should just be able to do something like this:

_your.service.ts_
```typescript
constructor(private ionApi: IonApiService) {
  if (HttpUtil.isLocalhost()) {
    this.ionApi.setDevelopmentToken(SOME_TOKEN);
  }
}

makeDatalakeRequest() {
  this.ionApi.execute({
    method: "POST",
    url: "IONSERVICES/datalakeapi/v1/compass/jobs?resultFormat=text/csv",
    headers: { Accept: "text/csv" },
    body: SOME_CONTENT,
    source: "some-unique-source"
  }).subscribe(
    response => console.log("Response:", response),
    error => console.error("Error:", error),
  );
}
```

_odin.json_
```json
{
    ...
    "/ODIN_DEV_TENANT": {
      "target": "https://mingle-ionapi.se2.inforcloudsuite.com",
      "secure": false,
      "headers": {
        "Origin": "https://localhost"
      },
      "changeOrigin": true,
      "pathRewrite": {
        "^/ODIN_DEV_TENANT": "/ALLIANCEGRP_DEV"
      },
      "logLevel": "debug"
    }
}
```

Then run `odin serve`.

Could you also try with the original sample code to see if are able to send requests to `Mingle/SocialService.svc/...`?

**Comment by alliancehaydenm** [comment]
Thanks for the info Andreas - making some progress here.

I'm now getting a 400 response on the HTTP call (using the ION sample code as well as my own datalake query code). The below screenshot is directly from the sample app.
![image](https://user-images.githubusercontent.com/62520530/81130939-8efffd00-8f9d-11ea-99ed-0b22becc72a3.png)

odin.json proxy as follows:
![image](https://user-images.githubusercontent.com/62520530/81130957-9f17dc80-8f9d-11ea-8286-4bfdb6bb4bfe.png)

**Comment by macalat** [comment]
Hi Andreas, I am successfully retrieving data from datalake from my local. 
![image](https://user-images.githubusercontent.com/4149858/84892507-48d7a680-b0d0-11ea-826e-53ba6a72509a.png)

However if i build and upload it in a live MT environment I am getting a CORS error for the POST request
![image](https://user-images.githubusercontent.com/4149858/84893029-2c883980-b0d1-11ea-9288-c9db619471c4.png)

I can verify that other ION Api such as `Mingle/SocialService.svc/ ` is working. 

Kindly advise if there are additional steps needed to make when creating a build for the application. I am using odin version 2.2.1

**Comment by karinpb** [comment]
@macalat Please use the code as suggested by Andreas.
Your issue seems to be related to setting withCredentials to true. See for example this: https://stackoverflow.com/questions/42803394/cors-credentials-mode-is-include

Postman does not work like a browser and using a proxy is not the same as when you deploy but you have probably added withCredentials here, which you should not do. If you still have issues is very hard for us to assist with all APIs that are available through ION API Gateway.

**Comment by macalat** [comment]
Hello @karinpb thank you for pointing me on the correct direction on what to look at. My request is the same as Andreas's example, without the `withCredentials`. I tried explicitly setting this to `false` for my ION api request but it is still not working.

However upon further digging, i found that some options for all http request are being overwritten with default value, one of this is `withCredentials` being set to `true `https://github.com/infor-cloud/m3-h5-sdk/blob/master/m3-odin/projects/infor-up/m3-odin-angular/src/lib/service.ts

**Comment by karinpb** [comment]
Interesting, if ION API uses this IHttpService then it is always true. You can always clone the repro and change that and test.

**Comment by macalat** [comment]
For quick testing, i updated the code in my `node_modules`, build the project and then upload it. The datalake **POST** is now working from **MT**
![image](https://user-images.githubusercontent.com/4149858/84910721-ceb41b80-b0e9-11ea-9bf4-d2ac649dc2e8.png)

**Comment by anhallbe** [comment]
@macalat thanks for finding that!
A fix has been added to version `next.5`. (https://github.com/infor-cloud/m3-h5-sdk/releases/tag/v3.0.0-next.5).

Hopefully everything should work now. Although these CORS issues keep popping up in different environments/browsers/endpoints so I'm afraid this is not the last one. Feel free to try it out, though!
