### ISSUE TITLE
bug userService: UserService

### ISSUE THREAD

**Issue by mcaterin** [infor-cloud/m3-h5-sdk#43]
Bonjour,
Le support d'infor m'a redirigé ici.
Nous avons un bug avec votre solution  dans les informations utilisateurs.

Voici la fonction utilisé dans mon code pour obtenir les informations de l'utilisateurs :
constructor(private miService: MIService,
private userService: UserService) {}

load() {

this.userService.getUserContext().subscribe((userContext: IUserContext) => {
console.log(userContext);
this.userContext = userContext;
}, (error) => {

console.log('Unable to get userContext ' + error);
});
}

Cela est fournis par infor via votre gitHub.

Lorsque j'ouvre M3 et que je lance la page créée par mon développement, on peut voir les informations utilisateur obtenues via votre fonction.
Je les fais afficher dans un console log.

Sur l'image default_value.PNG , ce sont bien mes valeurs par défaut.
Ensuite je referme la page pour me retrouver au menu principal de M3 H5 et j'effectue la commande CMP500065 pour changer de DIVI ( CMP500065.PNG et CMP500065_confirm.PNG)
Quand j'ouvre à nouveau la page la valeur de CurrentDivision n'est pas correcte. Elle est de 060 et devrait être 065. Par contre la valeur dans CurrentDivisionName est juste (resultat.PNG).

Voici tous les éléments dont je dispose.

default_value.PNG:
![default_value](https://user-images.githubusercontent.com/65290002/81811753-6fc91880-9525-11ea-8d5b-9a92bbd96c4a.PNG)

CMP500065.PNG : 
![CMP500065](https://user-images.githubusercontent.com/65290002/81811788-7c4d7100-9525-11ea-863f-e138824b50f6.PNG)

CMP500065_confirm.PNG:
![CMP500065_confirm](https://user-images.githubusercontent.com/65290002/81811813-84a5ac00-9525-11ea-8558-a5d8877c9b08.PNG)

resultat.PNG
![resultat](https://user-images.githubusercontent.com/65290002/81811833-8c655080-9525-11ea-91b6-87de76ab051c.PNG)

Merci d'avance pour votre aide

Cordialement
**Version**
"@infor-up/m3-odin": "2.1.2",
"@infor-up/m3-odin-angular": "2.1.2",
"@infor-up/m3-odin-cli": "^2.2.1",

**Comment by DXCdhenningsver** [comment]
Hi,

This should have been solved in version 2.2.1, see this issue:
https://github.com/infor-cloud/m3-h5-sdk/issues/27

**Comment by mcaterin** [comment]
Merci pour votre réponse.
Mais je n'arrive pas à mettre à jour en 2.2.1

voici ce que j'ai :
npm update @infor-up/m3-odin --loglevel verbose        
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'update',
npm verb cli   '@infor-up/m3-odin',
npm verb cli   'verbose'
npm verb cli ]
npm info using npm@6.12.1
npm info using node@v12.13.1
npm verb npm-session acc06458f0e387e8
npm verb update computing outdated modules to update
npm http fetch GET 200 https://registry.npmjs.org/@infor-up%2fm3-odin 214ms
npm verb outdated not updating @infor-up/m3-odin because it's currently at the maximum version that matches its specified semver range
npm verb exit [ 0, true ]
npm timing npm Completed in 4835ms
npm info ok

**Comment by DXCdhenningsver** [comment]
In this thread you will find some information about upgrading an existing project:
https://github.com/infor-cloud/m3-h5-sdk/issues/37

**Comment by mcaterin** [comment]
Ok.
J'ai enlever le node-modules et vérifié dans package.json que tout était bon.
J'ai pu faire la Maj et le bug est bien corrigé.
Merci de votre aide
Désolé je débute ^^
