### ISSUE TITLE
Impact of KB 2096424 on H5 SDK

### ISSUE THREAD

**Issue by shyam-leanswift** [infor-cloud/m3-h5-sdk#45]
## Description
I think this doesn't have any impact on the M3 H5 SDK. However since the description in the KB itself is unclear I just want confirmation from the dev team on whether this is something we need to worry about or not.

Quoting from the KB:

> Reason for the change: The ION API Gateway in Infor OS is providing better tools for API management. 
> 
> Result of the change: Current usage of M3 Business Authentication will no longer be possible.
> 
> Who does this affect: Anyone who develops applications integrating with M3 CE, e.g. Infor M3 CE customers, Infor Consulting Services and Infor partners.
> 
> Actions required prior to activating the change:
> 
> With immediate effect, no new solutions should be designed or developed using M3 BE Authentication. 
> 
> More information about the different options is available in the free webinar Infor OS: Developing API Gateway authorized applications and in the documentation Infor ION API Administration Guide.
> 
> Existing use of M3 BE Authentication will need to be changed to ION API Gateway over the coming months. Support will be terminated September 2020.

**Comment by karinpb** [comment]
Hi Shyam,
H5 SDK applications run within H5 and are not affected by the KB you are quoting. I’ve previously asked them to clarify this with a few examples, but it seems like it’s not been updated. I’m sorry about that.

Rest assured, you don’t need to switch to ION API for MI calls. You do however need to update to the latest version of the SDK to get CSRF protection when calling the M3 MI API in M3 CE.
