### ISSUE TITLE
Is that possible to launch a bookmark url from H5 client?

### ISSUE THREAD

**Issue by Xiang-Ji615** [infor-cloud/m3-h5-sdk#46]
Can I pls ask if that's possible to launch a bookmark url from H5 client?
Thx.

**Comment by karinpb** [comment]
Hi,
An example of the type of link you are thinking about would have been helpful. Try and install the sample app and try the link that you would like to use in that app.

Also try the link with just the query part, starting with ?xxxxx.

**Comment by Xiang-Ji615** [comment]
Thx. The bookmark is as below.

<Bookmark>
      <type>link</type>
      <name>MMS001/H</name>
      <url>?favoriteContext=bookmark%3FMMS001%26MITMAS%26MMCONO%252C790%252CMMITNO%252CAIT100%252B%252B%252B%252B%252B%252B%252B%252B%252B%265%26H%26MMS001%252FH&amp;LogicalId=lid://infor.m3</url>
      <id>637069454914400000</id>
      <DisplayOrder>3</DisplayOrder>
    </Bookmark>

Thx in advance.

**Comment by Xiang-Ji615** [comment]
Basically we have a H5 SDK app running as Infor homepage widget and are trying to launch a bookmark so we can go to MMS001/H with one click as a example.
Thx.

**Comment by karinpb** [comment]
Hi,
I’m on PTO today so I’m not going to decode the URL to actually check the syntax but it seems wrong. Where is this Xml coming from? I recognize?favoriteconext, but then the last parameter should be &LogicalId=lid://Infor.m3.1, notice that you need to full logicalId here or the Mingle drillback will never work.

1. Add the launch example as a widget and try just the URL - after fixing it

2. Then try and use the app service as the sample does and let me know if it works or not.

There are a lot of limitations to running the H5 SDK app outside of H5, you should only be using MI APIs and you will always be using the default cono and divi from MNS150. 

You are running M3CE right? Native Homepages widgets are way better that having av IFrame. I do hope that it will be possible for you all to build tenant widgets in the future.

**Comment by Xiang-Ji615** [comment]
The URL is from Infor OS->Bookmarks.
![image](https://user-images.githubusercontent.com/25782375/82636071-1eb3d580-9c45-11ea-92f7-575497758d28.png)

The app service only works in H5 context but not as web widget.
![image](https://user-images.githubusercontent.com/25782375/82636112-41de8500-9c45-11ea-913a-bba57d4e619b.png)
I am running out of idea to launch a bookmark.
Thx in advance.

**Comment by karinpb** [comment]
@anhallbe Can you please see if there is any way to launch through the Infor Companyon in this case? I mean launching other applications within H5 is a valid scenario as well. If there is no option to do so then answer the question as no, it's not possible and then we need to discuss if we should do it as an enhancement.

**Comment by anhallbe** [comment]
In order to launch bookmarks when running outside of H5 you'd need the Infor Companyon Client. This is not included in the SDK right now, but it's possible that it will be added as a future enhancement. Although that is not decided yet.
