### ISSUE TITLE
When opening bookmarks, fieldNames values are not set in the program inerface

### ISSUE THREAD

**Issue by devdln** [infor-cloud/m3-h5-sdk#47]
Tried opening a bookmark with following code, bookmark opens successfully. But Item No, Warehouse fields are missing the values in the fieldNames field.

Also generated URL from Bookmark.toUri method didn't have the fieldNames section.

Below is the code.

let bookmark: IBookmark = {
      program: "MMS081",
      fieldNames: "WHLO,WHL,ITNO,LBITEM1ME080,FACI,UNMS,WHGR",
      table: "MITBAL",
      keyNames: "MBCONO,MBWHLO,MBITNO",
      isStateless: false,
    };
    bookmark.values = {
      MBCONO: '771',
      MBWHLO: 'WHL',
      MBITNO: 'LBITEM1ME080',
    };
let url: string = Bookmark.toUri(bookmark);
ApplicationService.launch(url);

**Comment by anhallbe** [comment]
@karinpb could you clarify what's wrong here?

IIRC the property names in the `IBookmark.values` must match the `IBookmark.fieldNames`. But I'm not that familiar with bookmarks, so I might be wrong..

**Comment by prkarlsson** [comment]
The fieldNames property is used to set additional values that are not part of the primary key. Exactly which fields that needs to be set varies between programs. In some cases you don't need to duplicate fields that are part of the primary key, sometimes you do.  The names of the fields should be the the names of the fields on the panel.

For MMS081 the field names for the panel header are:
Item number: WWITNO
Facility: W1FACI
Whs group: WWWHGR
Whs: W1WHLO

If you want to set all these the fieldNames property should be be defined like this:

fieldNames: "WWITNO,W1FACI,WWWHGR,W1WHLO"


The values for the fields must then be available in the bookmark values dictionary. 

**Example values (for keys & fields):**
```
bookmark.values = {
    MBCONO: '771',
    MBWHLO: 'WHL',
    MBITNO: 'LBITEM1ME080',
    WWITNO: 'LBITEM1ME080',
    W1FACI: 'A01',
    WWWHGR: 'SA',
    W1WHLO: 'WHL'
};
```
