### ISSUE TITLE
Drag and drop of a cell in data grid - is it possible?

### ISSUE THREAD

**Issue by aleste37** [infor-cloud/m3-h5-sdk#48]
Hi,

In SDK v1/AngularJS -- I implemented a drag and drop using  github.com/fatlinesofcode/ngDraggable in an nglist . In a grid of stores in rows, and shoe sizes in the columns, it was used for easy drag and drop of stock between stores.  Is there something similar that might work with the included data grid in  the current sdk?

Thanks,
Jonathan
![Annotation 2020-05-29 142134](https://user-images.githubusercontent.com/19818335/83221094-372d6e00-a1b8-11ea-908f-7e541a0bf77a.png)

**Comment by anhallbe** [comment]
That (if it exists) would be part of the `ids-enterprise-ng` package. I haven't seen this feature used or implemented, but you could ask around over in the [GitHub project](https://github.com/infor-design/enterprise-ng) or in the [MS Teams channel](https://teams.microsoft.com/l/channel/19%3a83173693057f4991b7a84f030975c06d%40thread.skype/Angular%2520Components?groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&tenantId=457d5685-0467-4d05-b23b-8f817adda47c)
