### ISSUE TITLE
404 Error when authnticating ION API from H5sdk application.  W

### ISSUE THREAD

**Issue by avdheshpaliwal** [infor-cloud/m3-h5-sdk#52]
We are infor OS on-prem customer.

From h5sdk application IONAPIService looks for the endpoint in M3 Grid instead of in Infor OS Grid, 
ion API is trying to authenticate by calling following URL and throwing 404 https://apgm3sonprd.oldcastle.corp:21110/grid/rest/security/sessions/oauth

Please let us know  there is anything  can be done to change to make that work.
 
Because of this issue we cannot call any ION APIs from h5sdk.

**Comment by karinpb** [comment]
M3 On-prem grid does not support getting the OAuth token and they have said that it is too much work to push that functionality down to the 1.13 grid. One option would be for M3 on prem to update to the Grid 2.0 grid but I can't answer on if there is a plan for that or not.

H5 SDK does not support calling ION API for M3 on -prem. This is a known limitation that we need to mention more clearly in the read me file @anhallbe .

There is nothing else we can do. Please contact M3 support with your concerns and ask for when they will support calling ION API Gateway from either H5 SDK app or JavaScript.

Only IDM can be called. ION API Gateway is new functionality so I can understand that you can't push all new features into existing versions of the Software. We do have to focus on innovations and new versions.
