### ISSUE TITLE
MIService execute method not working in local development environment

### ISSUE THREAD

**Issue by devdln** [infor-cloud/m3-h5-sdk#54]
MIService execute method not working in local development environment because it's using the localhost URL, instead of the multi tenant URL as shown in the image.

![Capture](https://user-images.githubusercontent.com/65847848/85575778-78009180-b655-11ea-8a7e-7a31f59ab5af.JPG)

**Comment by anhallbe** [comment]
All requests are sent to localhost during development. The proxy started with `odin serve` is responsible for forwarding requests to the configured environment.
