### ISSUE TITLE
Export data from the sohodatagrid in excel and csv not working

### ISSUE THREAD

**Issue by GauravJags** [infor-cloud/m3-h5-sdk#59]
**Describe the bug**
When export to excel and export to csv is used in sohodatagrid. The excel doesnot contains the column headers from the datagrid.Also the same issue occurs with csv.

I had raised a issue https://github.com/infor-design/enterprise/issues/4081 which is now resolved.

However i am not sure how i can use the same in my already created odin cli project?

**To Reproduce**

**Expected behavior**

**Version**
 - `@infor-up/m3-odin`: version
 - `@infor-up/m3-odin-angular`: version
 - `@infor-up/m3-odin-cli`: version

**Additional context**

**Comment by tmcconechy** [comment]
Looks like the IDS sample project at https://github.com/infor-cloud/m3-h5-sdk/blob/master/m3-odin/samples/infor-m3-odin-sample-soho-3.0.1.zip might be what yours looks like. Then just update package.json entry:

`"ids-enterprise-ng": "~7.2.0",`

To   `"ids-enterprise-ng": "~7.4.1",`

Would be my guess?

**Comment by anhallbe** [comment]
Closing this as the issue has been fixed
