### ISSUE TITLE
Close the H5 tab running the H5 SDK app

### ISSUE THREAD

**Issue by chrisonline** [infor-cloud/m3-h5-sdk#62]
Is there a way to close the H5 tab via code where the H5 SDK app is running?

**Comment by anhallbe** [comment]
I don't think there's a H5 API for this. It would have to be added.

Just for clarification, you want the app inside the tab to close itself, right? Or do you want to close it from some external app/script, e.g H5 script?

**Comment by anhallbe** [comment]
This will be added to a later version of H5 (Most likely CE only).

Wrappers for the API may be added to the this SDK later as well. Keeping the issue open in the meantime.

**Comment by chrisonline** [comment]
> 
> Just for clarification, you want the app inside the tab to close itself, right? Or do you want to close it from some external app/script, e.g H5 script?
> 

I want to close it from the H5 App, so the user does not need to tap on "x" at the to.

**Comment by anhallbe** [comment]
Update: You can send the following message to H5 from inside the app:

```typescript
const message = JSON.stringify({
  type: "unload-tab",
  data: {
    tabId: document.body.getAttribute("h5tab"),
  }
});
window.parent.postMessage(message)
```

The "H5Tab" interface may still be added in the future, but I'm closing this ticket.
