### ISSUE TITLE
H5 tab name

### ISSUE THREAD

**Issue by chrisonline** [infor-cloud/m3-h5-sdk#63]
If we launch the H5 SDK app as a new tab via H5 script the tab name header is called 'mne/apps/sdkappname'.
Is there a way to rename this to a user friendly name?

![image](https://user-images.githubusercontent.com/2077218/88636560-60d01c00-d0b9-11ea-8d2a-64e9a2af0d5e.png)

**Comment by anhallbe** [comment]
Are you using `ScriptUtil.Launch()`? Depending on which version you are on, you could try adding the title as the second parameter, e.g `ScriptUtil.Launch("url", "title of the tab")`

**Comment by chrisonline** [comment]
Thanks!

We start the app via H5 Scripting, but  `ScriptUtil.Launch()` does not support a second parameter.
On which H5 Scripting version should this be working? I think we are on the newest so far as I know ;-)

**Comment by anhallbe** [comment]
This functionality & docs has now been fixed/added to MUA version 10.4.1.20200310-070321, so it should be possible to set the title using `ScriptUtil.Launch()` with that version.

AFAIK this is only in CE, and not on-prem. But I'm not 100% sure on that.
