### ISSUE TITLE
Filter sohodatagrid single column for multiple values and return the result

### ISSUE THREAD

**Issue by FranklinAf** [infor-cloud/m3-h5-sdk#69]
Filtering on a single column, for the multiple values 'test', 'test2', and 'test3'.

`const filter: SohoDataGridFilterCondition[] = [
         { columnId: 'col-sup', operator: 'contains', value: ('test' || 'test2' || 'test3') },
      ];`

If the column has any of those values, return all rows in the filtered result.

Thanks!

**Comment by anhallbe** [comment]
Hi @FranklinAf !
I think you'll have a better chance of getting an answer to this question over in the `ids-enterprise-ng` project: https://github.com/infor-design/enterprise-ng
