### ISSUE TITLE
UserService.getUserContext() does not update CurrentDivision

### ISSUE THREAD

**Issue by MarcJonquet** [infor-cloud/m3-h5-sdk#7]
Hello,
We need to switch between 3 M3 divisions (020, 030, 060) in a unique company. 
On M3 we do that with CMP001020, CMP001030 and CMP001060 commands.

We have installed "Example H5-SDK SOHO" and go to User Context Page and check the user parameters. The CurrentDivisionName parameter is changing but not CurrentDivision.

Thank you for your help.

**Comment by anhallbe** [comment]
Fixed in 2.2.1
