### ISSUE TITLE
login utility for MAC OS

### ISSUE THREAD

**Issue by sudhakaran-samadurai** [infor-cloud/m3-h5-sdk#70]
The login utility in the code base is 'exe' which supports for windows operating system, Could you please let me know if there is a logic utility available to connect with MT in MAC OS.

**Comment by anhallbe** [comment]
Yes! There is an `experimental-login` command that replicates the functionality of the login utility. See https://github.com/infor-cloud/m3-h5-sdk/issues/55#issuecomment-651713612
