### ISSUE TITLE
Log to grid logs?

### ISSUE THREAD

**Issue by cerjoh** [infor-cloud/m3-h5-sdk#73]
Hi,

Is it possible to log to the grid logs from an application? Client side logging through console is of course always available, but we need a way to centralize log entries from the applications.

Thanks!

**Comment by karinpb** [comment]
Hi,
I understand the requirement but there is no such endpoint in H5 / MUA, or in the grid. I'm hesitant to that they would add such endpoint for SDK apps to call unless it's completely de-coupled from MUA / H5 or there is some rate limiting checks in place. Log tampering is also a vulnerability to handle so any data passed as input would have to be strictly validated. It seems like an easy feature to provide, but it isn't.

It's out of scope for the M3 H5 SDK.

I understand the need to know if there are client issues but it's a not as straight forward to just provide and endpoint to where you can log anything and it ends up in a log in the grid. I recommend you to build your own or create an enhancement request on M3. The focus for new development is Cloud, in which case you can't check the grid logs so it would in fact have to be something else, like a tool.

**Comment by cerjoh** [comment]
Thanks Karin for a quick and comprehensive reply! We'll have to find another way around this. Short term, this will most likely be to store logs client-side that can be downloaded and sent for analysis. Long term perhaps expose a third party REST endpoint for central logging.
