### ISSUE TITLE
Can you send/receive JSON messages from H5SDK to be received on a widget 

### ISSUE THREAD

**Issue by drirem0** [infor-cloud/m3-h5-sdk#74]
I know that you can send and receive message types between homepage widgets. Then M3 sends 'inforbusinesscontext', which is also clear and we can consume this messagetype in homepage widget space.

But what about sending a messagetype from an M3 H5SDK application ? 

As infor.Companyon is not available yet in H5SDK., is there any other way of sending a messagetype from M3H5SDK which I then can consume elsewhere in a contextual widget ?

Thanks very much

**Comment by anhallbe** [comment]
The Companyon client is not included in the SDK for various reasons (licensing, versioning, project scope etc.). But if you can get a hold of the client script, you could perhaps still use it in your application?

You could also try replicating the behavior you want with `window.top.postMessage(....)`.

I haven't really tried this, but I'm pretty sure it would work.

Note that we are investigating whether it would be possible/a good idea to include the companyon client in the SDK as well.

**Comment by anhallbe** [comment]
The companyon client will not be distributed with the H5 SDK in the near future. Please contact Ryan Bavery for further questions regarding this.

**Comment by kimanderssonm3cs** [comment]
Hi!
Even though it wont be distributed with the H5 SDK, is it still possible to trigger the message towards the Context Viewer?

I can see your window.top.postMessage(...) but that's gonna be hard to bruteforce without any more information.. Is there any more information about the Context Viewer/Business Context somewhere?

**Comment by LSenadheera** [comment]
@kimanderssonm3cs @drirem0 

Hey,
Were you able to read the context JSON via the H5 SDK?
