### ISSUE TITLE
Does this SDK support IDM?

### ISSUE THREAD

**Issue by shyam-leanswift** [infor-cloud/m3-h5-sdk#8]
Is there a recommended way to access IDM APIs using this SDK  or do I have to resort to using the default http service provided by Angular? I don't find anything related to IDM in the README. So in case you have something for this, it would be good to add it there.

**Comment by shyam-leanswift** [comment]
@karinpb Do you have any information about this?

**Comment by anhallbe** [comment]
Hello! You can either use the Angular HTTP client, or the ION API service to talk to IDM.

There is a sample showing how to perform a search in IDM. It shows how to talk to IDM with both the Angular HTTP client, and the ION API service, depending on whether the app is running in a MT or on-prem environment.

**Comment by shyam-leanswift** [comment]
@anhallbe Thank you. I found it out afterwards.
