### ISSUE TITLE
Yes, these classes are for interacting with M3 screens. However, the documentation for these are intentionally left out since interactive programs are too complex for most developers and should only ever be used for edge cases. It can be used for custom rendering of stateless detail panels started using a bookmark.

### ISSUE THREAD

**Issue by Ouse** [infor-cloud/m3-h5-sdk#80]
Yes, these classes are for interacting with M3 screens. However, the documentation for these are intentionally left out since interactive programs are too complex for most developers and should only ever be used for edge cases. It can be used for custom rendering of stateless detail panels started using a bookmark.

There is a basic example of using the FormService in the "bookmark" sample.

_Originally posted by @anhallbe in https://github.com/infor-cloud/m3-h5-sdk/issues/66#issuecomment-693255885_

**Comment by Ouse** [comment]
Hi,

I checked that sample Bookmarks, and as you mention it is read-only.

So the 'best' way to approach requirements where a panel in M3 needs to added to a sdk, like we composed screens with the old Smart Office Mashups Designer will be to avoid it and try to list M3 APIs?, even if we lose the M3 functionality to it?.

Tack!.

**Comment by anhallbe** [comment]
Duplicate #66
