### ISSUE TITLE
DataGrid, is there a possiblity to change deafult filter setting?

### ISSUE THREAD

**Issue by bjohog** [infor-cloud/m3-h5-sdk#81]
Hi,

is there a possibility to change the default filter setting Contains, say for example that I want to use Starts with instead as default setting?

![image](https://user-images.githubusercontent.com/39406230/104693896-b00f1500-570a-11eb-989e-74bf317add1c.png)

**Comment by tmcconechy** [comment]
This is probably a question for https://github.com/infor-design/enterprise but i can answer it...

Answer is there is an option you can see in this example https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-custom-filter-conditions.html#L27-L30 where you can change the filter conditions for a column (option filterConditions)

**Comment by bjohog** [comment]
Thanks!

It works perfectly.
