### ISSUE TITLE
Is it possible to deploy automatically on H5 from gitlab ?

### ISSUE THREAD

**Issue by cdasilvacosta** [infor-cloud/m3-h5-sdk#82]
Hello,
For my developments I use Gitlab with different pipelines to build the application. But I can't find a solution to deploy the zip without having to go to the H5 administrator page.

Do you know a method to deploy the application zip without having to go through the administrator area on the web interface?

Thank you !

**Comment by karinpb** [comment]
Hi,
The API to upload is not a published API. It’s a form upload in the UI. To make a REST API for this that we allow external systems to use would first require a new API to be developed, but we would only consider adding it for cloud and in cloud you would still not be able to authenticate with SAML from your CI/CD in git. That means that the requirement is not only to expose the API but also to allow access with OAuth for example, perhaps from ION API. What you need to do is contact support and add an enhancement request, but adding this is not an easy task and there is a manual way to do it. To be honest it’s not likely to get prioritized unless you get a lot of votes for the requirement. I understand the requirement and thank you for sharing. I’ll let the team at least know the question came up.

Regards
Karin
