### ISSUE TITLE
[Question] Is it possible to use bookmark in local mode for CE multi-tenant?

### ISSUE THREAD

**Issue by mbenmoussati** [infor-cloud/m3-h5-sdk#83]
Hi,
## Description
I encounter error using non stateless bookmarks in local mode in CE. 
I'm using :
 this.formService.executeBookmark(bookmark); to open it and 
this.formService.executeCommand('CLOSE', this.instanceId).subscribe((r) => { 
         });
to close the instance.

When executed inside H5 in CE env, it works fine. the bookmark opens.

In Local dev mode, i've an error : 
HTTP ERROR: 400 Bad Request
Problem accessing /mne/servlet/MvxMCSvt
Bad Request

i start my app using :  
odin login ..... 
and
odin serve --multi-tenant

FYI : Requests to  /m3api-rest works fine both in local mode / deployed in H5
Thanks

## Versions
Odin : Version 4.0.0
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.0.4
@angular/cli                    11.0.7
@angular/material               11.0.4
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.5.5
typescript                      4.0.5

**Comment by anhallbe** [comment]
Hi @mbenmoussati !
`/mne` requests do not work through ION API. I think this might be the issue since the default operation for the `login` command is to log in to the environment, get an ION API token, and configure `odin.json` accordingly.

For bookmarks to work locally, you'll need to add the `--m3` argument:

```
odin login -c --m3 https://theurltom3 ./path/to/file.ionapi
odin serve --multi-tenant
```

**Comment by mbenmoussati** [comment]
Thank you @anhallbe !!!

**Comment by perravnborg** [comment]
I have tried the following:
odin login -c --m3 https://m3prdeuc1.m3.eu1.inforcloudsuite.com ./ION/odin.ionapi

and it sends up the popup for sign on - but when I press Allow - the following error occurs:
Logon request failed (urn:oasis:names:tc:SAML:2.0:status:Responder - STATUS-MISSING - Unexpected Runtime Authn Adapter Integration Problem.) (error: 612)

NB! "odin login -c ./ION/odin.ionapi" works

Do you have a hint? Thx
