### ISSUE TITLE
Calling M3 program in angular/odin

### ISSUE THREAD

**Issue by MaamounMil** [infor-cloud/m3-h5-sdk#85]
Hi,

I am beginner with development of angualar / M3 Odin on H5 .

I don't find how to integrate a M3 program or a M3 program window on my application .

I now that there are the M3 APIs but I'm looking for the solution to integrate all the program (call the m3 program on my application ).

Could you guide me please

Best Regards

**Comment by Owaiii** [comment]
Hello,

Call M3 program in mashup => Bookmark

https://github.com/infor-cloud/m3-h5-sdk/tree/master/m3-odin/src/app/material-app/samples/bookmark

**Comment by MaamounMil** [comment]
Hello ,
this tutorial shows how to call a simple bookmark. My problem is how to call a mashup screen in my angular/ODIN project .
Thank you for your answer .
Regards

**Comment by anhallbe** [comment]
Hi!
Embedding M3 screens in an application (through iframes or other means) is outside the scope of this SDK.
