### ISSUE TITLE
Not able to establish connection to MT 

### ISSUE THREAD

**Issue by JyrkiKankaanpaa** [infor-cloud/m3-h5-sdk#9]
I started Odin SDK Longin Utility M3 only.
 Navigate odin.json in my project
 Set tentant url and M3 url.
 Click Verify => M3 server responded!
 Click Login Tap I get login window
 Login => Tentants start screen flaches and turn blank.
Login expires shows - and progress bar stay green
 Start odin serve
Navigate Chrome localhost index, cllick load => CORS error
Starting Chrome again by --new-window --disable-web-security  => no CORS error by no data either

![sdk1](https://user-images.githubusercontent.com/8567593/68871835-bb7d3f80-0705-11ea-82f1-a38bdefeed22.jpg)
![sdk2](https://user-images.githubusercontent.com/8567593/68871843-be783000-0705-11ea-9959-1e823555c80b.jpg)
![sdk3](https://user-images.githubusercontent.com/8567593/68871857-c46e1100-0705-11ea-821c-165876dc0893.jpg)
![sdk4](https://user-images.githubusercontent.com/8567593/68871868-c8019800-0705-11ea-8386-8f539774e581.jpg)
![sdk5](https://user-images.githubusercontent.com/8567593/68871876-cafc8880-0705-11ea-859e-04c8bbe9b66b.jpg)
![sdk6](https://user-images.githubusercontent.com/8567593/68871880-cc2db580-0705-11ea-9558-9a173fdef677.jpg)

 Br Jyka

**Comment by anhallbe** [comment]
Can you try adding the `--multi-tenant` flag when starting the dev server?

I.e `odin serve --multi-tenant`

**Comment by JyrkiKankaanpaa** [comment]
HI! Thanks!! That I missed. Br Jyka
