### ISSUE TITLE
AngularJS app to Angular

### ISSUE THREAD

**Issue by mbenmoussati** [infor-cloud/m3-h5-sdk#91]
Hi, 
Is there a way to easily migrate AngularJs apps to Angular? 
Or does exist a version of Odin for AngularJs using Csrf? Since the recent update of Infor OS all our mashups developped with Angularjs doesn't work anymore. 
this is because of the csrf token. 
Thank you for your help.

**Comment by karinpb** [comment]
Hi,
There is no easy way to update and Odinv2 is more focused on APIs than UI controls.

But there is an updated version of Odinv1 that you can download through Infor support.

https://infor.flexnetoperations.com/control/epny/download?cert_num=110738632&element=5563711&dkey=17188577&plne=648511
